### ISSUE TITLE
Card redesign

### ISSUE THREAD

**Issue by martinlarsson** [t4ed/ikt-inventering#12]
The grid layout with card works great but the actual design of each card can be improved. A bit dull in the current iteration. The amount of pixels for rounded corners matches the rest of application (Bootstrap standard) quite badly.

See https://www.webdesignerdepot.com/2017/01/50-creative-card-ui-designs/ for inspiration.

**Comment by Balkfisk** [comment]
Fixed rounded corners and put descriptive text in a fixed position.
