### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by martinlarsson** [t4ed/ikt-inventering#19]
Parser Error
Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Unexpected "{" after "@" character. Once inside the body of a code block (@if {}, @{}, etc.) you do not need to use "@{" to switch to code.

https://github.com/t4ed/ikt-inventering/blob/dfb8eaaf289bcf930a3ed18a76d93af02f633d39/ikt/ikt/Views/Ikts/Create.cshtml#L46

**Comment by marcusperhamn** [comment]
Fixed
