### ISSUE TITLE
"Årskurs" increment sends data automatically

### ISSUE THREAD

**Issue by martinlarsson** [t4ed/ikt-inventering#25]
When incrementing the "Årskurs" field in /Projects/Create the form is sent automatically(?) and results in invalid data.

[![https://gyazo.com/d554b23886d3cab812b08590756a2ec4](https://i.gyazo.com/d554b23886d3cab812b08590756a2ec4.gif)](https://gyazo.com/d554b23886d3cab812b08590756a2ec4)

**Comment by martinlarsson** [comment]
The Edit page seems to behave in a similiar manner (but data is not invalid here):
[![https://gyazo.com/4a29da4056d67f0ff475720ccf7b3af2](https://i.gyazo.com/4a29da4056d67f0ff475720ccf7b3af2.gif)](https://gyazo.com/4a29da4056d67f0ff475720ccf7b3af2)

**Comment by Balkfisk** [comment]
Fixed
