### ISSUE TITLE
Bootstrap blue

### ISSUE THREAD

**Issue by martinlarsson** [t4ed/ikt-inventering#9]
The standard Bootstrap blue is mixed with the custom color scheme(?)

![bootstrap-blue](https://user-images.githubusercontent.com/7649793/36905592-099645c0-1e34-11e8-9b83-98520bfbfd07.png)

**Comment by johu96** [comment]
Fixed focus light colours

**Comment by johu96** [comment]
Fixed paging colours aswell.

**Comment by johu96** [comment]
Input active colour is still blue...

**Comment by johu96** [comment]
PDF input will be fixed due christoffers changes
